### ISSUE TITLE
NativeFileDialog should emit a signal when the dialog is closed without selecting anything

### ISSUE THREAD

**Issue by tonebacas** [98teg/NativeDialogs#12]
There is an unhandled scenario where the user might not select anything when a NativeFileDialog pops up, and instead dismiss it entirely; there is no signal to handle this situation, such that we might respond to it.

For example, it might be relevant to know if the user has opted to save a file when prompted to do so, and in case they dismiss the popup, we might warn them about possible loss of unsaved data.

**Comment by 98teg** [comment]
That's a good point, I would add a `cancelled` signal to `NativeFileDialog`.
