### ISSUE TITLE
Godot 4 support

### ISSUE THREAD

**Issue by aaronfranke** [98teg/NativeDialogs#2]
I would find it useful if this addon worked with Godot 4 alphas/betas, any chance that it can be ported?

**Comment by 98teg** [comment]
HI! Thank you for showing interest! Godot 4 has deprecated GDNative and replaced it with GDExtensions. It would require rewriting the plugin. I still plan to do so, but the last time I checked the documentation for GDExtensions wasn't complete. I would give it a go now that we are closer to the betas, and if everything comes alone I would let you know.

**Comment by 98teg** [comment]
The port is now complete in this branch https://github.com/98teg/NativeDialogs/tree/godot-4.0! There may be some things that may be added in the future, but I would close this request since right now it is usable. Thanks!
