### ISSUE TITLE
Color Picker Dialog

### ISSUE THREAD

**Issue by GevDevs** [98teg/NativeDialogs#3]
Being able to use an OS's native color picker would be a nice addition to the addon.

Edit: Checked the library that this plugin is based on and it seems that the library doesn't have this option. Maybe I should make a suggestion there instead.

**Comment by 98teg** [comment]
Sure! I also think `portable-file-dialogs` could benefit from that feature, so it is a good idea to suggest it there if it hasn't already. But I'm also open to new features not present in `portable-file-dialogs`, though I would need a lightweight C/C++ library suggestion to consider it.
