### ISSUE TITLE
Dialog titles show garbled characters if filters are set

### ISSUE THREAD

**Issue by madrxx** [98teg/NativeDialogs#31]
Hi, I have two NativeFileDialogs as children of the root Control node in my project. Whether I have Mode Overrides Title selected or not, the dialog boxes sometimes show the file types in their title instead, or sometimes show garbled characters. This only occurs if I set filters on the dialog, either by using the Godot Inspector pane, or by using the .add_filter() method.

To reproduce: create a NativeFileDialog, put filters on it, call it with show(), close it with the mouse and then call .show() again. If it does not occur yet, close it again and open it again with show(). It occurs within 2-4 attempts consistently for me.

![image](https://github.com/98teg/NativeDialogs/assets/74277456/8b59289a-8c0d-4597-a920-2ad6d0d1700d)
![image](https://github.com/98teg/NativeDialogs/assets/74277456/9b164b6a-427f-4339-8362-84475031db48)
![image](https://github.com/98teg/NativeDialogs/assets/74277456/b515cbb4-7015-4fd0-9678-214ee47503aa)
![image](https://github.com/98teg/NativeDialogs/assets/74277456/8d143609-b86b-4878-8682-8fde22511823)
![image](https://github.com/98teg/NativeDialogs/assets/74277456/317987a2-b066-4147-998e-d496e15edc4f)

**Comment by 98teg** [comment]
Please, check if this version of the plugin fixes the issue. I'm not sure about how the code change that I made fixes the issue, but it seems to be working for me.

[native_dialogs.zip](https://github.com/98teg/NativeDialogs/files/14593818/native_dialogs.zip)

**Comment by madrxx** [comment]
Working for me also, thanks.
