### ISSUE TITLE
Support for web builds

### ISSUE THREAD

**Issue by Zettexe** [98teg/NativeDialogs#8]
Seems like this addon doesn't support web exports, not sure if its due to changes in Godot 4 or if it never supported web but it would be nice if it worked.

![image](https://user-images.githubusercontent.com/53223513/205493535-86ad20e9-a032-44ec-9030-ebee9029ee9f.png)

**Comment by 98teg** [comment]
Sadly it is not possible. The web is pretty restrictive in how it allows you to interact with the OS, as a browser operates in its own sandbox. I recommend executing JavaScript directly using the [JavaScript singleton](https://docs.godotengine.org/en/stable/classes/class_javascript.html).

**Comment by Zettexe** [comment]
Oh I didn't know about being able to run Javascript from Godot, that will work just fine for my purposes.
